// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package io.github.pmackowski.rsocket.raft.client.protobuf;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 members = 1;</code>
   */
  java.util.List<java.lang.Integer> getMembersList();
  /**
   * <code>repeated int32 members = 1;</code>
   */
  int getMembersCount();
  /**
   * <code>repeated int32 members = 1;</code>
   */
  int getMembers(int index);
}
