// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gossip.proto

package io.github.zomky.gossip.protobuf;

public interface GossipOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Gossip)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Gossip.Suspicion suspicion = 1;</code>
   */
  int getSuspicionValue();
  /**
   * <code>.Gossip.Suspicion suspicion = 1;</code>
   */
  io.github.zomky.gossip.protobuf.Gossip.Suspicion getSuspicion();

  /**
   * <code>int32 incarnation = 2;</code>
   */
  int getIncarnation();

  /**
   * <code>int32 node_id = 3;</code>
   */
  int getNodeId();
}
