// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gossip.proto

package io.github.zomky.gossip.protobuf;

/**
 * Protobuf type {@code Gossip}
 */
public  final class Gossip extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Gossip)
    GossipOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Gossip.newBuilder() to construct.
  private Gossip(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Gossip() {
    suspicion_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Gossip();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Gossip(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            suspicion_ = rawValue;
            break;
          }
          case 16: {

            incarnation_ = input.readInt32();
            break;
          }
          case 24: {

            nodeId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.zomky.gossip.protobuf.GossipOuterClass.internal_static_Gossip_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.zomky.gossip.protobuf.GossipOuterClass.internal_static_Gossip_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.zomky.gossip.protobuf.Gossip.class, io.github.zomky.gossip.protobuf.Gossip.Builder.class);
  }

  /**
   * Protobuf enum {@code Gossip.Suspicion}
   */
  public enum Suspicion
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>ALIVE = 1;</code>
     */
    ALIVE(1),
    /**
     * <code>SUSPECT = 2;</code>
     */
    SUSPECT(2),
    /**
     * <code>DEAD = 3;</code>
     */
    DEAD(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>ALIVE = 1;</code>
     */
    public static final int ALIVE_VALUE = 1;
    /**
     * <code>SUSPECT = 2;</code>
     */
    public static final int SUSPECT_VALUE = 2;
    /**
     * <code>DEAD = 3;</code>
     */
    public static final int DEAD_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Suspicion valueOf(int value) {
      return forNumber(value);
    }

    public static Suspicion forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return ALIVE;
        case 2: return SUSPECT;
        case 3: return DEAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Suspicion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Suspicion> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Suspicion>() {
            public Suspicion findValueByNumber(int number) {
              return Suspicion.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.github.zomky.gossip.protobuf.Gossip.getDescriptor().getEnumTypes().get(0);
    }

    private static final Suspicion[] VALUES = values();

    public static Suspicion valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Suspicion(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Gossip.Suspicion)
  }

  public static final int SUSPICION_FIELD_NUMBER = 1;
  private int suspicion_;
  /**
   * <code>.Gossip.Suspicion suspicion = 1;</code>
   */
  public int getSuspicionValue() {
    return suspicion_;
  }
  /**
   * <code>.Gossip.Suspicion suspicion = 1;</code>
   */
  public io.github.zomky.gossip.protobuf.Gossip.Suspicion getSuspicion() {
    @SuppressWarnings("deprecation")
    io.github.zomky.gossip.protobuf.Gossip.Suspicion result = io.github.zomky.gossip.protobuf.Gossip.Suspicion.valueOf(suspicion_);
    return result == null ? io.github.zomky.gossip.protobuf.Gossip.Suspicion.UNRECOGNIZED : result;
  }

  public static final int INCARNATION_FIELD_NUMBER = 2;
  private int incarnation_;
  /**
   * <code>int32 incarnation = 2;</code>
   */
  public int getIncarnation() {
    return incarnation_;
  }

  public static final int NODE_ID_FIELD_NUMBER = 3;
  private int nodeId_;
  /**
   * <code>int32 node_id = 3;</code>
   */
  public int getNodeId() {
    return nodeId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (suspicion_ != io.github.zomky.gossip.protobuf.Gossip.Suspicion.UNKNOWN.getNumber()) {
      output.writeEnum(1, suspicion_);
    }
    if (incarnation_ != 0) {
      output.writeInt32(2, incarnation_);
    }
    if (nodeId_ != 0) {
      output.writeInt32(3, nodeId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (suspicion_ != io.github.zomky.gossip.protobuf.Gossip.Suspicion.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, suspicion_);
    }
    if (incarnation_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, incarnation_);
    }
    if (nodeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, nodeId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.zomky.gossip.protobuf.Gossip)) {
      return super.equals(obj);
    }
    io.github.zomky.gossip.protobuf.Gossip other = (io.github.zomky.gossip.protobuf.Gossip) obj;

    if (suspicion_ != other.suspicion_) return false;
    if (getIncarnation()
        != other.getIncarnation()) return false;
    if (getNodeId()
        != other.getNodeId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUSPICION_FIELD_NUMBER;
    hash = (53 * hash) + suspicion_;
    hash = (37 * hash) + INCARNATION_FIELD_NUMBER;
    hash = (53 * hash) + getIncarnation();
    hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.zomky.gossip.protobuf.Gossip parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.zomky.gossip.protobuf.Gossip prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Gossip}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Gossip)
      io.github.zomky.gossip.protobuf.GossipOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.zomky.gossip.protobuf.GossipOuterClass.internal_static_Gossip_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.zomky.gossip.protobuf.GossipOuterClass.internal_static_Gossip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.zomky.gossip.protobuf.Gossip.class, io.github.zomky.gossip.protobuf.Gossip.Builder.class);
    }

    // Construct using io.github.zomky.gossip.protobuf.Gossip.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      suspicion_ = 0;

      incarnation_ = 0;

      nodeId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.zomky.gossip.protobuf.GossipOuterClass.internal_static_Gossip_descriptor;
    }

    @java.lang.Override
    public io.github.zomky.gossip.protobuf.Gossip getDefaultInstanceForType() {
      return io.github.zomky.gossip.protobuf.Gossip.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.zomky.gossip.protobuf.Gossip build() {
      io.github.zomky.gossip.protobuf.Gossip result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.zomky.gossip.protobuf.Gossip buildPartial() {
      io.github.zomky.gossip.protobuf.Gossip result = new io.github.zomky.gossip.protobuf.Gossip(this);
      result.suspicion_ = suspicion_;
      result.incarnation_ = incarnation_;
      result.nodeId_ = nodeId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.zomky.gossip.protobuf.Gossip) {
        return mergeFrom((io.github.zomky.gossip.protobuf.Gossip)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.zomky.gossip.protobuf.Gossip other) {
      if (other == io.github.zomky.gossip.protobuf.Gossip.getDefaultInstance()) return this;
      if (other.suspicion_ != 0) {
        setSuspicionValue(other.getSuspicionValue());
      }
      if (other.getIncarnation() != 0) {
        setIncarnation(other.getIncarnation());
      }
      if (other.getNodeId() != 0) {
        setNodeId(other.getNodeId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.zomky.gossip.protobuf.Gossip parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.zomky.gossip.protobuf.Gossip) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int suspicion_ = 0;
    /**
     * <code>.Gossip.Suspicion suspicion = 1;</code>
     */
    public int getSuspicionValue() {
      return suspicion_;
    }
    /**
     * <code>.Gossip.Suspicion suspicion = 1;</code>
     */
    public Builder setSuspicionValue(int value) {
      suspicion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Gossip.Suspicion suspicion = 1;</code>
     */
    public io.github.zomky.gossip.protobuf.Gossip.Suspicion getSuspicion() {
      @SuppressWarnings("deprecation")
      io.github.zomky.gossip.protobuf.Gossip.Suspicion result = io.github.zomky.gossip.protobuf.Gossip.Suspicion.valueOf(suspicion_);
      return result == null ? io.github.zomky.gossip.protobuf.Gossip.Suspicion.UNRECOGNIZED : result;
    }
    /**
     * <code>.Gossip.Suspicion suspicion = 1;</code>
     */
    public Builder setSuspicion(io.github.zomky.gossip.protobuf.Gossip.Suspicion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      suspicion_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Gossip.Suspicion suspicion = 1;</code>
     */
    public Builder clearSuspicion() {
      
      suspicion_ = 0;
      onChanged();
      return this;
    }

    private int incarnation_ ;
    /**
     * <code>int32 incarnation = 2;</code>
     */
    public int getIncarnation() {
      return incarnation_;
    }
    /**
     * <code>int32 incarnation = 2;</code>
     */
    public Builder setIncarnation(int value) {
      
      incarnation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 incarnation = 2;</code>
     */
    public Builder clearIncarnation() {
      
      incarnation_ = 0;
      onChanged();
      return this;
    }

    private int nodeId_ ;
    /**
     * <code>int32 node_id = 3;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }
    /**
     * <code>int32 node_id = 3;</code>
     */
    public Builder setNodeId(int value) {
      
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 node_id = 3;</code>
     */
    public Builder clearNodeId() {
      
      nodeId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Gossip)
  }

  // @@protoc_insertion_point(class_scope:Gossip)
  private static final io.github.zomky.gossip.protobuf.Gossip DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.zomky.gossip.protobuf.Gossip();
  }

  public static io.github.zomky.gossip.protobuf.Gossip getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Gossip>
      PARSER = new com.google.protobuf.AbstractParser<Gossip>() {
    @java.lang.Override
    public Gossip parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Gossip(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Gossip> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Gossip> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.zomky.gossip.protobuf.Gossip getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

