// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gossip.proto

package io.github.zomky.gossip.protobuf;

public interface InitJoinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitJoinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
