// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gossip.proto

package io.github.zomky.gossip.protobuf;

public interface JoinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JoinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>repeated .Gossip gossips = 2;</code>
   */
  java.util.List<io.github.zomky.gossip.protobuf.Gossip> 
      getGossipsList();
  /**
   * <code>repeated .Gossip gossips = 2;</code>
   */
  io.github.zomky.gossip.protobuf.Gossip getGossips(int index);
  /**
   * <code>repeated .Gossip gossips = 2;</code>
   */
  int getGossipsCount();
  /**
   * <code>repeated .Gossip gossips = 2;</code>
   */
  java.util.List<? extends io.github.zomky.gossip.protobuf.GossipOrBuilder> 
      getGossipsOrBuilderList();
  /**
   * <code>repeated .Gossip gossips = 2;</code>
   */
  io.github.zomky.gossip.protobuf.GossipOrBuilder getGossipsOrBuilder(
      int index);
}
