// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.zomky.transport.protobuf;

public interface AddGroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddGroupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * OK if group was added successfully
   * </pre>
   *
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
