// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.zomky.transport.protobuf;

/**
 * Protobuf type {@code AppendEntriesRequest}
 */
public  final class AppendEntriesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AppendEntriesRequest)
    AppendEntriesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppendEntriesRequest.newBuilder() to construct.
  private AppendEntriesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppendEntriesRequest() {
    entries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppendEntriesRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppendEntriesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            term_ = input.readInt32();
            break;
          }
          case 16: {

            leaderId_ = input.readInt32();
            break;
          }
          case 24: {

            prevLogIndex_ = input.readInt64();
            break;
          }
          case 32: {

            prevLogTerm_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              entries_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            entries_.add(input.readBytes());
            break;
          }
          case 48: {

            leaderCommit_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        entries_ = java.util.Collections.unmodifiableList(entries_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.zomky.transport.protobuf.Raft.internal_static_AppendEntriesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.zomky.transport.protobuf.Raft.internal_static_AppendEntriesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.zomky.transport.protobuf.AppendEntriesRequest.class, io.github.zomky.transport.protobuf.AppendEntriesRequest.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 1;
  private int term_;
  /**
   * <pre>
   * set leader’s term
   * </pre>
   *
   * <code>int32 term = 1;</code>
   */
  public int getTerm() {
    return term_;
  }

  public static final int LEADER_ID_FIELD_NUMBER = 2;
  private int leaderId_;
  /**
   * <pre>
   * leaderId so follower can redirect clients
   * </pre>
   *
   * <code>int32 leader_id = 2;</code>
   */
  public int getLeaderId() {
    return leaderId_;
  }

  public static final int PREV_LOG_INDEX_FIELD_NUMBER = 3;
  private long prevLogIndex_;
  /**
   * <pre>
   * index of log entry immediately preceding new ones
   * </pre>
   *
   * <code>int64 prev_log_index = 3;</code>
   */
  public long getPrevLogIndex() {
    return prevLogIndex_;
  }

  public static final int PREV_LOG_TERM_FIELD_NUMBER = 4;
  private long prevLogTerm_;
  /**
   * <pre>
   * term of prevLogIndex entry
   * </pre>
   *
   * <code>int64 prev_log_term = 4;</code>
   */
  public long getPrevLogTerm() {
    return prevLogTerm_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 5;
  private java.util.List<com.google.protobuf.ByteString> entries_;
  /**
   * <pre>
   * log entries to store (empty for heartbeat may send more than one for efficiency)
   * </pre>
   *
   * <code>repeated bytes entries = 5;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getEntriesList() {
    return entries_;
  }
  /**
   * <pre>
   * log entries to store (empty for heartbeat may send more than one for efficiency)
   * </pre>
   *
   * <code>repeated bytes entries = 5;</code>
   */
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <pre>
   * log entries to store (empty for heartbeat may send more than one for efficiency)
   * </pre>
   *
   * <code>repeated bytes entries = 5;</code>
   */
  public com.google.protobuf.ByteString getEntries(int index) {
    return entries_.get(index);
  }

  public static final int LEADER_COMMIT_FIELD_NUMBER = 6;
  private long leaderCommit_;
  /**
   * <pre>
   * leader’s commitIndex
   * </pre>
   *
   * <code>int64 leader_commit = 6;</code>
   */
  public long getLeaderCommit() {
    return leaderCommit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0) {
      output.writeInt32(1, term_);
    }
    if (leaderId_ != 0) {
      output.writeInt32(2, leaderId_);
    }
    if (prevLogIndex_ != 0L) {
      output.writeInt64(3, prevLogIndex_);
    }
    if (prevLogTerm_ != 0L) {
      output.writeInt64(4, prevLogTerm_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      output.writeBytes(5, entries_.get(i));
    }
    if (leaderCommit_ != 0L) {
      output.writeInt64(6, leaderCommit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, term_);
    }
    if (leaderId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, leaderId_);
    }
    if (prevLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, prevLogIndex_);
    }
    if (prevLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, prevLogTerm_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < entries_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(entries_.get(i));
      }
      size += dataSize;
      size += 1 * getEntriesList().size();
    }
    if (leaderCommit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, leaderCommit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.zomky.transport.protobuf.AppendEntriesRequest)) {
      return super.equals(obj);
    }
    io.github.zomky.transport.protobuf.AppendEntriesRequest other = (io.github.zomky.transport.protobuf.AppendEntriesRequest) obj;

    if (getTerm()
        != other.getTerm()) return false;
    if (getLeaderId()
        != other.getLeaderId()) return false;
    if (getPrevLogIndex()
        != other.getPrevLogIndex()) return false;
    if (getPrevLogTerm()
        != other.getPrevLogTerm()) return false;
    if (!getEntriesList()
        .equals(other.getEntriesList())) return false;
    if (getLeaderCommit()
        != other.getLeaderCommit()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderId();
    hash = (37 * hash) + PREV_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrevLogIndex());
    hash = (37 * hash) + PREV_LOG_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrevLogTerm());
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (37 * hash) + LEADER_COMMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeaderCommit());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.zomky.transport.protobuf.AppendEntriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.zomky.transport.protobuf.AppendEntriesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AppendEntriesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AppendEntriesRequest)
      io.github.zomky.transport.protobuf.AppendEntriesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.zomky.transport.protobuf.Raft.internal_static_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.zomky.transport.protobuf.Raft.internal_static_AppendEntriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.zomky.transport.protobuf.AppendEntriesRequest.class, io.github.zomky.transport.protobuf.AppendEntriesRequest.Builder.class);
    }

    // Construct using io.github.zomky.transport.protobuf.AppendEntriesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      term_ = 0;

      leaderId_ = 0;

      prevLogIndex_ = 0L;

      prevLogTerm_ = 0L;

      entries_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      leaderCommit_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.zomky.transport.protobuf.Raft.internal_static_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    public io.github.zomky.transport.protobuf.AppendEntriesRequest getDefaultInstanceForType() {
      return io.github.zomky.transport.protobuf.AppendEntriesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.zomky.transport.protobuf.AppendEntriesRequest build() {
      io.github.zomky.transport.protobuf.AppendEntriesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.zomky.transport.protobuf.AppendEntriesRequest buildPartial() {
      io.github.zomky.transport.protobuf.AppendEntriesRequest result = new io.github.zomky.transport.protobuf.AppendEntriesRequest(this);
      int from_bitField0_ = bitField0_;
      result.term_ = term_;
      result.leaderId_ = leaderId_;
      result.prevLogIndex_ = prevLogIndex_;
      result.prevLogTerm_ = prevLogTerm_;
      if (((bitField0_ & 0x00000001) != 0)) {
        entries_ = java.util.Collections.unmodifiableList(entries_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.entries_ = entries_;
      result.leaderCommit_ = leaderCommit_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.zomky.transport.protobuf.AppendEntriesRequest) {
        return mergeFrom((io.github.zomky.transport.protobuf.AppendEntriesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.zomky.transport.protobuf.AppendEntriesRequest other) {
      if (other == io.github.zomky.transport.protobuf.AppendEntriesRequest.getDefaultInstance()) return this;
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      if (other.getLeaderId() != 0) {
        setLeaderId(other.getLeaderId());
      }
      if (other.getPrevLogIndex() != 0L) {
        setPrevLogIndex(other.getPrevLogIndex());
      }
      if (other.getPrevLogTerm() != 0L) {
        setPrevLogTerm(other.getPrevLogTerm());
      }
      if (!other.entries_.isEmpty()) {
        if (entries_.isEmpty()) {
          entries_ = other.entries_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureEntriesIsMutable();
          entries_.addAll(other.entries_);
        }
        onChanged();
      }
      if (other.getLeaderCommit() != 0L) {
        setLeaderCommit(other.getLeaderCommit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.zomky.transport.protobuf.AppendEntriesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.zomky.transport.protobuf.AppendEntriesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int term_ ;
    /**
     * <pre>
     * set leader’s term
     * </pre>
     *
     * <code>int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }
    /**
     * <pre>
     * set leader’s term
     * </pre>
     *
     * <code>int32 term = 1;</code>
     */
    public Builder setTerm(int value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * set leader’s term
     * </pre>
     *
     * <code>int32 term = 1;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0;
      onChanged();
      return this;
    }

    private int leaderId_ ;
    /**
     * <pre>
     * leaderId so follower can redirect clients
     * </pre>
     *
     * <code>int32 leader_id = 2;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }
    /**
     * <pre>
     * leaderId so follower can redirect clients
     * </pre>
     *
     * <code>int32 leader_id = 2;</code>
     */
    public Builder setLeaderId(int value) {
      
      leaderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * leaderId so follower can redirect clients
     * </pre>
     *
     * <code>int32 leader_id = 2;</code>
     */
    public Builder clearLeaderId() {
      
      leaderId_ = 0;
      onChanged();
      return this;
    }

    private long prevLogIndex_ ;
    /**
     * <pre>
     * index of log entry immediately preceding new ones
     * </pre>
     *
     * <code>int64 prev_log_index = 3;</code>
     */
    public long getPrevLogIndex() {
      return prevLogIndex_;
    }
    /**
     * <pre>
     * index of log entry immediately preceding new ones
     * </pre>
     *
     * <code>int64 prev_log_index = 3;</code>
     */
    public Builder setPrevLogIndex(long value) {
      
      prevLogIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * index of log entry immediately preceding new ones
     * </pre>
     *
     * <code>int64 prev_log_index = 3;</code>
     */
    public Builder clearPrevLogIndex() {
      
      prevLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long prevLogTerm_ ;
    /**
     * <pre>
     * term of prevLogIndex entry
     * </pre>
     *
     * <code>int64 prev_log_term = 4;</code>
     */
    public long getPrevLogTerm() {
      return prevLogTerm_;
    }
    /**
     * <pre>
     * term of prevLogIndex entry
     * </pre>
     *
     * <code>int64 prev_log_term = 4;</code>
     */
    public Builder setPrevLogTerm(long value) {
      
      prevLogTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * term of prevLogIndex entry
     * </pre>
     *
     * <code>int64 prev_log_term = 4;</code>
     */
    public Builder clearPrevLogTerm() {
      
      prevLogTerm_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> entries_ = java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entries_ = new java.util.ArrayList<com.google.protobuf.ByteString>(entries_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * log entries to store (empty for heartbeat may send more than one for efficiency)
     * </pre>
     *
     * <code>repeated bytes entries = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getEntriesList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(entries_) : entries_;
    }
    /**
     * <pre>
     * log entries to store (empty for heartbeat may send more than one for efficiency)
     * </pre>
     *
     * <code>repeated bytes entries = 5;</code>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <pre>
     * log entries to store (empty for heartbeat may send more than one for efficiency)
     * </pre>
     *
     * <code>repeated bytes entries = 5;</code>
     */
    public com.google.protobuf.ByteString getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <pre>
     * log entries to store (empty for heartbeat may send more than one for efficiency)
     * </pre>
     *
     * <code>repeated bytes entries = 5;</code>
     */
    public Builder setEntries(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
      entries_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * log entries to store (empty for heartbeat may send more than one for efficiency)
     * </pre>
     *
     * <code>repeated bytes entries = 5;</code>
     */
    public Builder addEntries(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
      entries_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * log entries to store (empty for heartbeat may send more than one for efficiency)
     * </pre>
     *
     * <code>repeated bytes entries = 5;</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureEntriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, entries_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * log entries to store (empty for heartbeat may send more than one for efficiency)
     * </pre>
     *
     * <code>repeated bytes entries = 5;</code>
     */
    public Builder clearEntries() {
      entries_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private long leaderCommit_ ;
    /**
     * <pre>
     * leader’s commitIndex
     * </pre>
     *
     * <code>int64 leader_commit = 6;</code>
     */
    public long getLeaderCommit() {
      return leaderCommit_;
    }
    /**
     * <pre>
     * leader’s commitIndex
     * </pre>
     *
     * <code>int64 leader_commit = 6;</code>
     */
    public Builder setLeaderCommit(long value) {
      
      leaderCommit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * leader’s commitIndex
     * </pre>
     *
     * <code>int64 leader_commit = 6;</code>
     */
    public Builder clearLeaderCommit() {
      
      leaderCommit_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AppendEntriesRequest)
  }

  // @@protoc_insertion_point(class_scope:AppendEntriesRequest)
  private static final io.github.zomky.transport.protobuf.AppendEntriesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.zomky.transport.protobuf.AppendEntriesRequest();
  }

  public static io.github.zomky.transport.protobuf.AppendEntriesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppendEntriesRequest>
      PARSER = new com.google.protobuf.AbstractParser<AppendEntriesRequest>() {
    @java.lang.Override
    public AppendEntriesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppendEntriesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppendEntriesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppendEntriesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.zomky.transport.protobuf.AppendEntriesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

