// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.zomky.transport.protobuf;

public interface AppendEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AppendEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * currentTerm, for leader to update itself
   * </pre>
   *
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();

  /**
   * <pre>
   * last log index, set only if success equals to false (extension to Raft)
   * </pre>
   *
   * <code>int64 last_log_index = 3;</code>
   */
  long getLastLogIndex();
}
