// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.zomky.transport.protobuf;

public interface HeartbeatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartbeatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .HeartbeatGroupStatus heartbeat_group_statuses = 1;</code>
   */
  java.util.List<io.github.zomky.transport.protobuf.HeartbeatGroupStatus> 
      getHeartbeatGroupStatusesList();
  /**
   * <code>repeated .HeartbeatGroupStatus heartbeat_group_statuses = 1;</code>
   */
  io.github.zomky.transport.protobuf.HeartbeatGroupStatus getHeartbeatGroupStatuses(int index);
  /**
   * <code>repeated .HeartbeatGroupStatus heartbeat_group_statuses = 1;</code>
   */
  int getHeartbeatGroupStatusesCount();
  /**
   * <code>repeated .HeartbeatGroupStatus heartbeat_group_statuses = 1;</code>
   */
  java.util.List<? extends io.github.zomky.transport.protobuf.HeartbeatGroupStatusOrBuilder> 
      getHeartbeatGroupStatusesOrBuilderList();
  /**
   * <code>repeated .HeartbeatGroupStatus heartbeat_group_statuses = 1;</code>
   */
  io.github.zomky.transport.protobuf.HeartbeatGroupStatusOrBuilder getHeartbeatGroupStatusesOrBuilder(
      int index);
}
