// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gossip.proto

package io.github.pmackowski.rsocket.raft.gossip.protobuf;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 initiator_node_id = 1;</code>
   */
  int getInitiatorNodeId();

  /**
   * <code>optional int32 requestor_node_id = 2;</code>
   */
  int getRequestorNodeId();

  /**
   * <code>optional int32 destination_node_id = 3;</code>
   */
  int getDestinationNodeId();

  /**
   * <code>optional bool direct = 4;</code>
   */
  boolean getDirect();

  /**
   * <code>optional int64 counter = 5;</code>
   */
  long getCounter();

  /**
   * <code>optional int32 nack_timeout = 6;</code>
   */
  int getNackTimeout();

  /**
   * <code>repeated .Gossip gossips = 7;</code>
   */
  java.util.List<io.github.pmackowski.rsocket.raft.gossip.protobuf.Gossip> 
      getGossipsList();
  /**
   * <code>repeated .Gossip gossips = 7;</code>
   */
  io.github.pmackowski.rsocket.raft.gossip.protobuf.Gossip getGossips(int index);
  /**
   * <code>repeated .Gossip gossips = 7;</code>
   */
  int getGossipsCount();
  /**
   * <code>repeated .Gossip gossips = 7;</code>
   */
  java.util.List<? extends io.github.pmackowski.rsocket.raft.gossip.protobuf.GossipOrBuilder> 
      getGossipsOrBuilderList();
  /**
   * <code>repeated .Gossip gossips = 7;</code>
   */
  io.github.pmackowski.rsocket.raft.gossip.protobuf.GossipOrBuilder getGossipsOrBuilder(
      int index);
}
