// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gossip.proto

package io.github.pmackowski.rsocket.raft.gossip.protobuf;

public interface PingReqRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingReqRequest)
    com.google.protobuf.MessageOrBuilder {
}
