// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gossip.proto

package io.github.pmackowski.rsocket.raft.gossip.protobuf;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool ack = 1;</code>
   */
  boolean getAck();
}
