// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package io.github.pmackowski.rsocket.raft.rpc;

public interface AppendEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AppendEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * currentTerm, for leader to update itself
   * </pre>
   *
   * <code>optional int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>optional bool success = 2;</code>
   */
  boolean getSuccess();
}
