// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.pmackowski.rsocket.raft.transport.protobuf;

public interface AddGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 leader_id_suggestion = 1;</code>
   */
  int getLeaderIdSuggestion();

  /**
   * <code>optional string state_machine = 2;</code>
   */
  java.lang.String getStateMachine();
  /**
   * <code>optional string state_machine = 2;</code>
   */
  com.google.protobuf.ByteString
      getStateMachineBytes();

  /**
   * <code>optional int32 election_timeout_min = 3;</code>
   */
  int getElectionTimeoutMin();

  /**
   * <code>optional int32 election_timeout_max = 4;</code>
   */
  int getElectionTimeoutMax();

  /**
   * <code>optional bool passive = 5;</code>
   */
  boolean getPassive();

  /**
   * <code>optional bool persistent_storage = 6;</code>
   */
  boolean getPersistentStorage();

  /**
   * <code>optional int32 segment_size = 7;</code>
   */
  int getSegmentSize();

  /**
   * <code>repeated int32 nodes = 8;</code>
   */
  java.util.List<java.lang.Integer> getNodesList();
  /**
   * <code>repeated int32 nodes = 8;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated int32 nodes = 8;</code>
   */
  int getNodes(int index);
}
