// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.pmackowski.rsocket.raft.transport.protobuf;

public interface AddServerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddServerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * address of server to add to configuration
   * </pre>
   *
   * <code>optional int32 new_server = 1;</code>
   */
  int getNewServer();
}
