// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.pmackowski.rsocket.raft.transport.protobuf;

public interface InstallSnapshotResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InstallSnapshotResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * currentTerm, for leader to update itself
   * </pre>
   *
   * <code>int32 term = 1;</code>
   */
  int getTerm();
}
