// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.pmackowski.rsocket.raft.transport.protobuf;

public interface PreVoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PreVoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * candidate’s term + 1
   * </pre>
   *
   * <code>optional int32 next_term = 1;</code>
   */
  int getNextTerm();

  /**
   * <pre>
   * candidate requesting vote
   * </pre>
   *
   * <code>optional int32 candidate_id = 2;</code>
   */
  int getCandidateId();

  /**
   * <pre>
   * index of candidate’s last log entry
   * </pre>
   *
   * <code>optional int64 last_log_index = 3;</code>
   */
  long getLastLogIndex();

  /**
   * <pre>
   * term of candidate’s last log entry
   * </pre>
   *
   * <code>optional int64 last_log_term = 4;</code>
   */
  long getLastLogTerm();
}
