// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.github.pmackowski.rsocket.raft.transport.protobuf;

public interface RemoveServerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RemoveServerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * address of server to remove from configuration
   * </pre>
   *
   * <code>int32 old_server = 1;</code>
   */
  int getOldServer();
}
