// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package io.github.zomky.client.protobuf;

public interface InfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoRequest)
    com.google.protobuf.MessageOrBuilder {
}
